export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_STAGE = 'UPDATE_STAGE';
export const ADD_FILE = 'ADD_FILE';
export const DELETE_FILE = 'DELETE_FILE';

export const RANK_IMAGES_START = 'RANK_IMAGES_START';
export const RANK_IMAGES_SUCCESS = 'RANK_IMAGES_SUCCESS';

export const FETCH_HASHTAGS_START = 'FETCH_HASHTAGS_START';
export const FETCH_HASHTAGS_SUCCESS = 'FETCH_HASHTAGS_SUCCESS';
export const SET_HASHTAGS = 'SET_HASHTAGS';
export const SET_PROFILE_IMAGE_SRC = 'SET_PROFILE_IMAGE_SRC'

export const TOGGLE_THEME = 'TOGGLE_THEME'