export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_STAGE = 'UPDATE_STAGE';
export const ADD_FILE = 'ADD_FILE';
export const DELETE_FILE = 'DELETE_FILE';

export const SEARCH_IMAGES_START = 'SEARCH_IMAGES_START';
export const SEARCH_IMAGES_SUCCESS = 'SEARCH_IMAGES_SUCCESS';